# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.bridgeIt.com:
  peer0.importer.bridgeIt.com:
  peer0.exporter.bridgeIt.com:
  peer0.custom.bridgeIt.com:
  peer0.importerBank.bridgeIt.com:
  peer0.insurance.bridgeIt.com:
networks:
  byfn:

services:

  orderer.bridgeIt.com:
    extends:
      file:  base/docker-compose-base.yaml
      service: orderer.bridgeIt.com
    container_name: orderer.bridgeIt.com
    networks:
      - byfn

  peer0.importer.bridgeIt.com:
    container_name: peer0.importer.bridgeIt.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.importer.bridgeIt.com
    networks:
      - byfn

  peer0.exporter.bridgeIt.com:
    container_name: peer0.exporter.bridgeIt.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.exporter.bridgeIt.com
    networks:
      - byfn

  peer0.custom.bridgeIt.com:
    container_name: peer0.custom.bridgeIt.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.custom.bridgeIt.com
    networks:
      - byfn

  peer0.importerBank.bridgeIt.com:
    container_name: peer0.importerBank.bridgeIt.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.importerBank.bridgeIt.com
    networks:
      - byfn

  peer0.insurance.bridgeIt.com:
    container_name: peer0.insurance.bridgeIt.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.insurance.bridgeIt.com
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.importer.bridgeIt.com:7051
      - CORE_PEER_LOCALMSPID=ImporterMSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/importer.bridgeIt.com/peers/peer0.importer.bridgeIt.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/importer.bridgeIt.com/peers/peer0.importer.bridgeIt.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/importer.bridgeIt.com/peers/peer0.importer.bridgeIt.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/importer.bridgeIt.com/users/Admin@importer.bridgeIt.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.bridgeIt.com
      - peer0.importer.bridgeIt.com
      - peer0.exporter.bridgeIt.com
      - peer0.custom.bridgeIt.com
      - peer0.importerBank.bridgeIt.com
      - peer0.insurance.bridgeIt.com
    networks:
      - byfn
