# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.bridgeIt.com:
  peer0.importer.bridgeIt.com:
  peer0.exporter.bridgeIt.com:
  peer0.custom.bridgeIt.com:
  peer0.importerBank.bridgeIt.com:
  peer0.insurance.bridgeIt.com:

networks:
  byfn:
services:
  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-importer
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.importer.bridgeIt.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.importer.bridgeIt.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/importer.bridgeIt.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerImporter
    networks:
      - byfn

  ca1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-exporter
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.exporter.bridgeIt.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.exporter.bridgeIt.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/exporter.bridgeIt.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerExporter
    networks:
      - byfn

  ca2:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-custom
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.custom.bridgeIt.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA3_PRIVATE_KEY
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.custom.bridgeIt.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA3_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/custom.bridgeIt.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerCustom
    networks:
      - byfn
  orderer.bridgeIt.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.bridgeIt.com
    container_name: orderer.bridgeIt.com
    networks:
      - byfn

  ca3:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-importerBank
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.importerBank.bridgeIt.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA4_PRIVATE_KEY
    ports:
      - "10054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.importerBank.bridgeIt.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA4_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/importerBank.bridgeIt.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerImporterBank
    networks:
      - byfn
  orderer.bridgeIt.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.bridgeIt.com
    container_name: orderer.bridgeIt.com
    networks:
      - byfn

  ca4:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-insurance
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.insurance.bridgeIt.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA5_PRIVATE_KEY
    ports:
      - "11054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.insurance.bridgeIt.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA5_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/insurance.bridgeIt.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerInsurance
    networks:
      - byfn

  orderer.bridgeIt.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.bridgeIt.com
    container_name: orderer.bridgeIt.com
    networks:
      - byfn

  peer0.importer.bridgeIt.com:
    container_name: peer0.importer.bridgeIt.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.importer.bridgeIt.com
    networks:
      - byfn

  peer0.exporter.bridgeIt.com:
    container_name: peer0.exporter.bridgeIt.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.exporter.bridgeIt.com
    networks:
      - byfn

  peer0.custom.bridgeIt.com:
    container_name: peer0.custom.bridgeIt.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.custom.bridgeIt.com
    networks:
      - byfn

  peer0.importerBank.bridgeIt.com:
    container_name: peer0.importerBank.bridgeIt.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.importerBank.bridgeIt.com
    networks:
      - byfn

  peer0.insurance.bridgeIt.com:
    container_name: peer0.insurance.bridgeIt.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.insurance.bridgeIt.com
    networks:
      - byfn
