NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.custom.bridgeIt.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.custom.bridgeIt.com-cert.pem
    OrganizationalUnitIdentifier: peer
