# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.bridgeIt.com:
   container_name: orderer.bridgeIt.com
   image: hyperledger/fabric-orderer:$IMAGE_TAG
   environment:
     - ORDERER_GENERAL_LOGLEVEL=INFO
     - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
     - ORDERER_GENERAL_GENESISMETHOD=file
     - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
     - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
     - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
     # enabled TLS
     - ORDERER_GENERAL_TLS_ENABLED=false
     - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
     - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
     - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
   working_dir: /opt/gopath/src/github.com/hyperledger/fabric
   command: orderer
   volumes:
   - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
   - ../crypto-config/ordererOrganizations/bridgeIt.com/orderers/orderer.bridgeIt.com/msp:/var/hyperledger/orderer/msp
   - ../crypto-config/ordererOrganizations/bridgeIt.com/orderers/orderer.bridgeIt.com/tls/:/var/hyperledger/orderer/tls
   - orderer.bridgeIt.com:/var/hyperledger/production/orderer
   ports:
     - 7050:7050

  peer0.importer.bridgeIt.com:
    container_name: peer0.importer.bridgeIt.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.importer.bridgeIt.com
      - CORE_PEER_ADDRESS=peer0.importer.bridgeIt.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.importer.bridgeIt.com:7051
      - CORE_PEER_LOCALMSPID=ImporterMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/importer.bridgeIt.com/peers/peer0.importer.bridgeIt.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/importer.bridgeIt.com/peers/peer0.importer.bridgeIt.com/tls:/etc/hyperledger/fabric/tls
        - peer0.importer.bridgeIt.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer0.exporter.bridgeIt.com:
    container_name: peer0.exporter.bridgeIt.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.exporter.bridgeIt.com
      - CORE_PEER_ADDRESS=peer0.exporter.bridgeIt.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.exporter.bridgeIt.com:7051
      - CORE_PEER_LOCALMSPID=ExporterMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/exporter.bridgeIt.com/peers/peer0.exporter.bridgeIt.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/exporter.bridgeIt.com/peers/peer0.exporter.bridgeIt.com/tls:/etc/hyperledger/fabric/tls
        - peer0.exporter.bridgeIt.com:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053

  peer0.custom.bridgeIt.com:
    container_name: peer0.custom.bridgeIt.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.custom.bridgeIt.com
      - CORE_PEER_ADDRESS=peer0.custom.bridgeIt.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.custom.bridgeIt.com:7051
      - CORE_PEER_LOCALMSPID=CustomMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/custom.bridgeIt.com/peers/peer0.custom.bridgeIt.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/custom.bridgeIt.com/peers/peer0.custom.bridgeIt.com/tls:/etc/hyperledger/fabric/tls
        - peer0.custom.bridgeIt.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053

  peer0.importerBank.bridgeIt.com:
    container_name: peer0.importerBank.bridgeIt.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.importerBank.bridgeIt.com
      - CORE_PEER_ADDRESS=peer0.importerBank.bridgeIt.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.importerBank.bridgeIt.com:7051
      - CORE_PEER_LOCALMSPID=ImporterBankMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/importerBank.bridgeIt.com/peers/peer0.importerBank.bridgeIt.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/importerBank.bridgeIt.com/peers/peer0.importerBank.bridgeIt.com/tls:/etc/hyperledger/fabric/tls
        - peer0.importerBank.bridgeIt.com:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053

  peer0.insurance.bridgeIt.com:
    container_name: peer0.insurance.bridgeIt.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.insurance.bridgeIt.com
      - CORE_PEER_ADDRESS=peer0.insurance.bridgeIt.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.insurance.bridgeIt.com:7051
      - CORE_PEER_LOCALMSPID=InsuranceMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/insurance.bridgeIt.com/peers/peer0.insurance.bridgeIt.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/insurance.bridgeIt.com/peers/peer0.insurance.bridgeIt.com/tls:/etc/hyperledger/fabric/tls
        - peer0.insurance.bridgeIt.com:/var/hyperledger/production
    ports:
      - 11051:7051
      - 11053:7053
